
development:
  adapter: postgresql
  encoding: unicode
  database: myblog_development
  pool: 5
  username: blog
  password: blog
  host: localhost
  port: 5432
  
test: &test
  adapter: postgresql
  encoding: unicode
  database: myblog_test
  pool: 5
  username: blog
  password: blog
  host: localhost
  port: 5432
